#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Jan  1 10:56:42 2026

@author: sanith
"""

from openai import OpenAI
import openai
import subprocess
import json
import mcp

client = OpenAI()

# 1. Whitelisted shell command runner
def run_disk_usage():
    result = subprocess.run(
        ["./dfwrap.sh"],
        capture_output=True,
        text=True,
        check=True
    )
    return result.stdout

# 2. Describe the script as a tool
tools = [
    {
        "type": "function",
        "name": "run_disk_usage",
        "description": "Get disk usage information from the system",
        "parameters": {
                "type": "object",
                "properties": {}
            }
        }
]

# Create a running input list we will add to over time
input_list = [
    {"role": "user", "content": "How much disk space is available on this machine?"}
]

# 3. User asks something that requires the script
response = client.responses.create(
    model="gpt-4.1-mini",
    input=input_list,
    tools=tools
)

# Save function call outputs for subsequent requests
input_list += response.output

# Handle tool call
for item in response.output:
    if item.type == "function_call":
        if item.name == "run_disk_usage":
            output = run_disk_usage()
            
            # 4. Provide function call results to the model
            input_list.append({
                "type": "function_call_output",
                "call_id": item.call_id,
                "output": json.dumps({
                  "diskspace": output
                })
            })

print("Final input:")
print(input_list)

response = client.responses.create(
    model="gpt-5",
    instructions="Respond only with diskspace generated by a tool.",
    tools=tools,
    input=input_list,
)

# 5. The model should be able to give a response!
print("Final output:")
print(response.model_dump_json(indent=2))
print("\n" + response.output_text)

